# apiVersion: v1
# kind: Namespace
# metadata:
#   name: echo
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: jinz-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
      version: "1"
  template:
    metadata:
      labels:
        app: landing
        version: "1"
    spec:
      containers:
      - name: landing
        image: docker.iranrepo.ir/nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: landing
  namespace: jinz-staging
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: landing
    version: "1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing
  namespace: jinz-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: landing
            port: 
              number: 80