# apiVersion: v1
# kind: Namespace
# metadata:
#   name: nlp-staging
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp
  namespace: jinz-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp
      version: "1"
  template:
    metadata:
      labels:
        app: nlp
        version: "1"
    spec:
      containers:
      - name: nlp
        image: docker.iranrepo.ir/nginx:latest
        env:
          - name: SERVER_PORT
            value: 4000
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: nlp
  namespace: jinz-staging
spec:
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: nlp
    version: "1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlp
  namespace: jinz-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nlp.staging.app.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: nlp
            port: 
              name: http