apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base/podinfo
  - ./echo
  - ./jinz
  - ./landing
  - ./nlp
  - ./webcrawler
# patches:
#   - path: podinfo-values.yaml
#     target:
#       kind: HelmRelease
