apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base/podinfo
  # - ../base/echo
  # - ../base/jinz
  - ../base/landing
  # - ../base/nlp
  # - ../base/webcrawler
patches:
#   - path: podinfo-values.yaml
#     target:
#       kind: HelmRelease
  - target:
      kind: Ingress
      name: landing
      namespace: jinz-base
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: landing
        namespace: jinz-staging
      spec:
        rules:
        - host: staging.app.io
