apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jinz-staging
resources:
  - app.yaml
patches:
  - target:
      kind: Ingress
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: landing
      spec:
        rules:
        - host: staging.app.io